name: Deploy to Google Cloud Run

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2

    - name: Configure gcloud project
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config list

    - name: Enable required APIs
      run: |
        gcloud services enable run.googleapis.com
        gcloud services enable cloudbuild.googleapis.com

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy radeon-ai \
          --source=. \
          --platform=managed \
          --region=us-central1 \
          --allow-unauthenticated \
          --port=8000 \
          --memory=1Gi \
          --cpu=1 \
          --timeout=300 \
          --max-instances=10 \
          --quiet

    - name: Get Service URL
      run: |
        SERVICE_URL=$(gcloud run services describe radeon-ai --region=us-central1 --format='value(status.url)')
        echo "🚀 Service deployed at: $SERVICE_URL"
        echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

    - name: Test deployment
      run: |
        curl -f $SERVICE_URL/api/health || echo "Health check failed"